#!/usr/bin/env python3
"""Compare the canonical Docker exec-server child with its Windows path proxy.

This is a model-free control-plane fixture.  It deliberately does not start
Codex App Server, read a CODEX_HOME, authenticate, call a model, or run an
evaluation.  It executes only the pinned remote child contract generated by
``feynman_remote_exec_environment`` and records fixed, payload-free lifecycle
facts for the direct and proxy paths.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
import threading
import time
import uuid
from typing import Any, BinaryIO, Callable, Mapping, TypedDict

try:
    from .feynman_path_mapping import CONTAINER_DESTINATIONS, native_mounts
    from .feynman_remote_exec_environment import expected_docker_args
    from .feynman_subscription_smoke_exec import _validate_startup_telemetry_snapshot
    from .feynman_subscription_startup_diagnostic import _proxy_telemetry_ready
    from .feynman_docker_runtime_probe import PROBE_IMAGE
except ImportError:
    from feynman_path_mapping import CONTAINER_DESTINATIONS, native_mounts
    from feynman_remote_exec_environment import expected_docker_args
    from feynman_subscription_smoke_exec import _validate_startup_telemetry_snapshot
    from feynman_subscription_startup_diagnostic import _proxy_telemetry_ready
    from feynman_docker_runtime_probe import PROBE_IMAGE


REPORT_SCHEMA_VERSION = 1
MAX_CAPTURE_BYTES = 262144
MAX_LINE_BYTES = 262144
DEFAULT_TIMEOUT_SECONDS = 30
MAX_TIMEOUT_SECONDS = 60
LIFECYCLE_MARKER = b"FEYNMAN_REMOTE_CHILD_LIFECYCLE_OK\n"
INITIALIZE_REQUEST = (
    b'{"jsonrpc":"2.0","id":1,"method":"initialize",'
    b'"params":{"clientName":"feynman-remote-child-diagnostic"}}\n'
)
SAFE_ENV_KEYS = (
    "PATH", "SystemRoot", "WINDIR", "ComSpec", "PATHEXT", "TEMP", "TMP",
)
MOUNT_KEYS = ("candidate_dir", "ephemeral_home", "codex_home", "temp_dir")
MOUNT_DESTINATIONS = tuple(CONTAINER_DESTINATIONS[key] for key in MOUNT_KEYS)


class _Capture(TypedDict):
    bytes: int
    sample: bytes
    truncated: bool
    read_error: bool
    drained: bool
    nonempty: bool


def _new_capture() -> _Capture:
    return {
        "bytes": 0,
        "sample": b"",
        "truncated": False,
        "read_error": False,
        "drained": False,
        "nonempty": False,
    }


def _drain(stream: BinaryIO, capture: _Capture,
           on_line: Callable[[bytes], None] | None = None) -> None:
    """Drain a process stream while retaining only a bounded private sample."""
    sample = bytearray()
    buffered = bytearray()
    try:
        while True:
            chunk = stream.read(65536)
            if not chunk:
                break
            capture["nonempty"] = True
            capture["bytes"] += len(chunk)
            remaining = MAX_CAPTURE_BYTES - len(sample)
            if remaining > 0:
                sample.extend(chunk[:remaining])
            if len(chunk) > remaining:
                capture["truncated"] = True
            if on_line is not None:
                buffered.extend(chunk)
                while True:
                    try:
                        end = buffered.index(10)
                    except ValueError:
                        break
                    line = bytes(buffered[:end + 1])
                    del buffered[:end + 1]
                    if len(line) > MAX_LINE_BYTES:
                        on_line(b"")
                    else:
                        on_line(line)
                if len(buffered) > MAX_LINE_BYTES:
                    buffered.clear()
                    on_line(b"")
    except (OSError, ValueError):
        capture["read_error"] = True
    finally:
        if on_line is not None and buffered:
            on_line(b"" if len(buffered) > MAX_LINE_BYTES else bytes(buffered))
        capture["sample"] = bytes(sample)
        capture["drained"] = True


def _safe_environment(docker_config: Path) -> dict[str, str]:
    """Construct the minimal process environment needed by the fixture."""
    value = {
        key: os.environ[key]
        for key in SAFE_ENV_KEYS
        if key in os.environ
    }
    # Docker reads this directory, never the protected Codex login home.  The
    # caller validates that the directory is an empty disposable fixture.
    value["DOCKER_CONFIG"] = str(docker_config)
    return value


def _safe_error_code(error: BaseException) -> str:
    if isinstance(error, ValueError):
        return "input-validation"
    if isinstance(error, subprocess.TimeoutExpired):
        return "process-timeout"
    if isinstance(error, PermissionError):
        return "process-access-denied"
    if isinstance(error, FileNotFoundError):
        return "executable-not-found"
    if isinstance(error, subprocess.SubprocessError):
        return "process-subprocess-error"
    if isinstance(error, OSError):
        return "process-os-error"
    return "process-error"


def _command_ok(value: Mapping[str, Any]) -> bool:
    return bool(
        value.get("process_started") is True
        and value.get("exit_code") == 0
        and value.get("timed_out") is False
        and value.get("stdin_write_failed") is False
        and value.get("stdout_drained") is True
        and value.get("stderr_drained") is True
        and value.get("stdout_read_error") is False
        and value.get("stderr_read_error") is False
    )


def _terminate_process(process: subprocess.Popen[bytes], deadline: float) -> bool:
    if process.poll() is not None:
        return True
    try:
        remaining = max(0.1, deadline - time.monotonic())
        if os.name == "nt":
            subprocess.run(
                ["taskkill", "/PID", str(process.pid), "/T", "/F"],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                check=False, timeout=min(5.0, remaining),
            )
        else:
            process.terminate()
    except (OSError, subprocess.SubprocessError):
        pass
    try:
        process.wait(timeout=max(0.1, deadline - time.monotonic()))
        return True
    except subprocess.TimeoutExpired:
        try:
            process.kill()
        except (OSError, ValueError):
            pass
        try:
            process.wait(timeout=max(0.1, deadline - time.monotonic()))
        except subprocess.TimeoutExpired:
            return False
        return True


def _process_result(value: dict[str, Any], stdout: _Capture,
                    stderr: _Capture, *, timed_out: bool,
                    stdin_write_failed: bool,
                    launch_error: str | None = None) -> dict[str, Any]:
    value.update({
        "process_started": launch_error is None,
        "exit_code": value.get("exit_code"),
        "timed_out": timed_out,
        "stdin_write_failed": stdin_write_failed,
        "stdout_bytes": stdout["bytes"],
        "stderr_bytes": stderr["bytes"],
        "stdout_drained": stdout["drained"],
        "stderr_drained": stderr["drained"],
        "stdout_read_error": stdout["read_error"],
        "stderr_read_error": stderr["read_error"],
        "stdout_truncated": stdout["truncated"],
        "stderr_truncated": stderr["truncated"],
        "stderr_nonempty": stderr["nonempty"],
        "launch_error": launch_error,
    })
    return value


def _run_process(command: list[str], *, env: Mapping[str, str], timeout: int,
                 input_data: bytes | None = None,
                 on_stdout_line: Callable[[bytes], None] | None = None,
                 response_event: threading.Event | None = None,
                 wait_for_response: bool = False) -> tuple[dict[str, Any], bytes]:
    """Run one bounded process and return only safe stream metadata and sample."""
    stdout = _new_capture()
    stderr = _new_capture()
    started = time.monotonic()
    try:
        process = subprocess.Popen(
            command,
            stdin=subprocess.PIPE if input_data is not None else subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=dict(env),
            bufsize=0,
        )
    except (OSError, subprocess.SubprocessError) as error:
        result = _process_result({"exit_code": None}, stdout, stderr,
                                 timed_out=False, stdin_write_failed=False,
                                 launch_error=_safe_error_code(error))
        return result, b""

    assert process.stdout is not None and process.stderr is not None
    stdout_thread = threading.Thread(
        target=_drain, args=(process.stdout, stdout, on_stdout_line),
        name="remote-child-stdout", daemon=True,
    )
    stderr_thread = threading.Thread(
        target=_drain, args=(process.stderr, stderr),
        name="remote-child-stderr", daemon=True,
    )
    stdout_thread.start()
    stderr_thread.start()
    stdin_write_failed = False
    timed_out = False
    deadline = started + timeout
    try:
        if input_data is not None:
            assert process.stdin is not None
            try:
                process.stdin.write(input_data)
                process.stdin.flush()
            except (BrokenPipeError, OSError):
                stdin_write_failed = True
        if wait_for_response and response_event is not None:
            while response_event.is_set() is False and process.poll() is None:
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    timed_out = True
                    break
                response_event.wait(timeout=min(0.05, remaining))
        if process.poll() is None and time.monotonic() >= deadline:
            timed_out = True
        if process.stdin is not None:
            try:
                process.stdin.close()
            except OSError:
                pass
        if timed_out:
            stopped = _terminate_process(process, time.monotonic() + 5)
            if not stopped:
                timed_out = True
        else:
            remaining = deadline - time.monotonic()
            try:
                process.wait(timeout=max(0.1, remaining))
            except subprocess.TimeoutExpired:
                timed_out = True
                _terminate_process(process, time.monotonic() + 5)
    finally:
        if process.stdin is not None:
            try:
                process.stdin.close()
            except OSError:
                pass
    stdout_thread.join(timeout=5)
    stderr_thread.join(timeout=5)
    for stream in (process.stdout, process.stderr):
        try:
            stream.close()
        except (OSError, ValueError):
            pass
    result = _process_result(
        {"exit_code": process.poll()}, stdout, stderr,
        timed_out=timed_out, stdin_write_failed=stdin_write_failed,
    )
    return result, stdout["sample"]


def _docker_command(docker: Path, config: Path, *args: str) -> list[str]:
    return [str(docker), "--config", str(config), *args]


def _container_presence(docker: Path, config: Path, name: str) -> dict[str, Any]:
    try:
        result = subprocess.run(
            _docker_command(
                docker, config, "ps", "-a", "--filter", f"name=^{name}$",
                "--format", "{{.Names}}",
            ),
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
            check=False, timeout=5, env=_safe_environment(config),
        )
    except (OSError, subprocess.SubprocessError):
        return {"status": "unavailable", "absent": False}
    if result.returncode != 0:
        return {"status": "unavailable", "absent": False}
    return {
        "status": "available" if not result.stdout.strip() else "occupied",
        "absent": not bool(result.stdout.strip()),
    }


def _container_absent(docker: Path, config: Path, name: str) -> bool:
    """Compatibility predicate; evidence callers use _container_presence."""
    return _container_presence(docker, config, name)["absent"] is True


def _inspect_named_container(docker: Path, config: Path, name: str) -> dict[str, Any]:
    try:
        result = subprocess.run(
            _docker_command(
                docker, config, "inspect", name, "--format",
                "{{.Name}}|{{.State.Status}}|{{.State.ExitCode}}",
            ),
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
            check=False, timeout=5, env=_safe_environment(config),
        )
    except (OSError, subprocess.SubprocessError):
        return {"available": False, "owned": False, "status": "unavailable", "exit_code": None}
    fields = result.stdout.decode("ascii", errors="ignore").strip().split("|")
    if result.returncode != 0 or len(fields) != 3:
        return {"available": False, "owned": False, "status": "unavailable", "exit_code": None}
    try:
        exit_code: int | None = int(fields[2])
    except ValueError:
        exit_code = None
    safe_states = {"created", "running", "paused", "restarting", "removing", "exited", "dead"}
    return {
        "available": True,
        "owned": fields[0] == "/" + name,
        "status": fields[1] if fields[1] in safe_states else "unknown",
        "exit_code": exit_code,
    }


def _cleanup_container(docker: Path, config: Path, name: str) -> dict[str, Any]:
    presence = _container_presence(docker, config, name)
    if presence["status"] == "available":
        return {"status": "absent", "verified": True}
    if presence["status"] == "unavailable":
        return {"status": "presence-check-unavailable", "verified": False}
    observation = _inspect_named_container(docker, config, name)
    if observation.get("owned") is not True:
        return {"status": "not-owned-or-unavailable", "verified": False}
    try:
        result = subprocess.run(
            _docker_command(docker, config, "rm", "-f", name),
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            check=False, timeout=5, env=_safe_environment(config),
        )
    except (OSError, subprocess.SubprocessError):
        return {"status": "remove-error", "verified": False}
    absent = _container_absent(docker, config, name)
    return {
        "status": "removed" if result.returncode == 0 else "remove-failed",
        "verified": result.returncode == 0 and absent,
    }


def _initialize_observation() -> dict[str, Any]:
    return {
        "expected_id_responses": 0,
        "initialize_successes": 0,
        "initialize_error_codes": {},
        "malformed_messages": 0,
        "non_json_lines": 0,
        "unexpected_id_responses": 0,
        "notifications_seen": 0,
    }


def _observe_initialize_line(line: bytes, observation: dict[str, Any],
                             event: threading.Event) -> None:
    if not line:
        observation["malformed_messages"] += 1
        return
    try:
        value = json.loads(line.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        observation["non_json_lines"] += 1
        return
    if not isinstance(value, dict):
        observation["malformed_messages"] += 1
        return
    identifier = value.get("id")
    if identifier is None:
        observation["notifications_seen"] += 1
        return
    if type(identifier) not in {int, str}:
        observation["malformed_messages"] += 1
        return
    if identifier != 1:
        observation["unexpected_id_responses"] += 1
        return
    observation["expected_id_responses"] += 1
    error = value.get("error")
    result = value.get("result")
    if isinstance(result, dict) and not isinstance(error, dict):
        observation["initialize_successes"] += 1
    elif isinstance(error, dict) and type(error.get("code")) is int:
        key = str(error["code"])
        codes = observation["initialize_error_codes"]
        codes[key] = codes.get(key, 0) + 1
    else:
        observation["malformed_messages"] += 1
    event.set()


def _rpc_passed(process: Mapping[str, Any], response: Mapping[str, Any],
                cleanup: Mapping[str, Any], telemetry: Mapping[str, Any] | None = None) -> bool:
    telemetry_ok = True if telemetry is None else bool(
        telemetry.get("available") is True
        and telemetry.get("schema_valid") is True
        and telemetry.get("complete") is True
        and telemetry.get("child_exit_code") == 0
        and telemetry.get("mapping_clean") is True
        and telemetry.get("correlated") is True
    )
    return bool(
        _command_ok(process)
        and response.get("expected_id_responses") == 1
        and response.get("initialize_successes") == 1
        and response.get("initialize_error_codes") == {}
        and response.get("malformed_messages") == 0
        and response.get("non_json_lines") == 0
        and response.get("unexpected_id_responses") == 0
        and cleanup.get("verified") is True
        and telemetry_ok
    )


def _canonical_profile(image: str) -> dict[str, Any]:
    return {
        "network_mode": "none",
        "read_only_mounts": [],
        "tmpfs_mounts": ["/tmp"],
        "run_as": "1000:1000",
        "read_write_mounts": list(MOUNT_DESTINATIONS),
        "candidate_env_keys": [
            "HOME", "CODEX_HOME", "PATH", "PYTHONDONTWRITEBYTECODE", "TMPDIR",
        ],
        "image": image,
    }


def _canonical_docker_args(paths: Mapping[str, str], image: str,
                           run_id: str) -> list[str]:
    job = {
        "run_id": run_id,
        "paths": {
            "candidate_dir": paths["candidate_dir"],
            "ephemeral_home": paths["ephemeral_home"],
            "codex_home": paths["codex_home"],
            "temp_dir": paths["temp_dir"],
        },
        "boundary": {"mounts": native_mounts(paths)},
    }
    return expected_docker_args(job, _canonical_profile(image))


def _lifecycle_create_args(docker_args: list[str], image: str) -> list[str]:
    if not docker_args or docker_args[0] != "run":
        raise ValueError("canonical Docker args must start with run")
    image_index = docker_args.index(image)
    return [
        "create", *docker_args[1:image_index], "--entrypoint", "/bin/echo",
        image, LIFECYCLE_MARKER.decode().rstrip("\r\n"),
    ]


def _name_from_args(docker_args: list[str]) -> str:
    try:
        index = docker_args.index("--name")
        name = docker_args[index + 1]
    except (ValueError, IndexError) as error:
        raise ValueError("canonical Docker args have no container name") from error
    if not name or any(char not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.-" for char in name):
        raise ValueError("diagnostic container name is not safe")
    return name


def _semantic_args(docker_args: list[str]) -> list[str]:
    result = list(docker_args)
    try:
        result[result.index("--name") + 1] = "<unique-container>"
    except (ValueError, IndexError):
        pass
    return result


def _mount_destinations(docker_args: list[str]) -> tuple[str, ...]:
    destinations: list[str] = []
    index = 0
    while index < len(docker_args):
        if docker_args[index] in {"-v", "--volume"} and index + 1 < len(docker_args):
            try:
                _, destination, _ = docker_args[index + 1].rsplit(":", 2)
            except ValueError:
                return ()
            destinations.append(destination)
            index += 2
            continue
        index += 1
    return tuple(destinations)


def _regular_file(path: Path, label: str) -> Path:
    value = path.expanduser().absolute()
    if value.is_symlink() or not value.is_file():
        raise ValueError(f"{label} must be a regular file")
    return value.resolve()


def _directory(path: Path, label: str, *, empty: bool = False) -> Path:
    value = path.expanduser().absolute()
    if value.is_symlink() or not value.is_dir():
        raise ValueError(f"{label} must be a real directory")
    resolved = value.resolve()
    if empty and any(resolved.iterdir()):
        raise ValueError(f"{label} must be an empty disposable directory")
    return resolved


def _prepare_fixture_root(root: Path) -> dict[str, str]:
    value = root.expanduser().absolute()
    if value.exists() or value.is_symlink():
        raise ValueError("fixture root must be a new directory")
    value.mkdir(parents=True)
    paths: dict[str, str] = {}
    for key, dirname in (
        ("candidate_dir", "candidate"),
        ("ephemeral_home", "home"),
        ("codex_home", "codex"),
        ("temp_dir", "temp"),
    ):
        directory = value / dirname
        directory.mkdir()
        paths[key] = str(directory.resolve())
    return paths


def _validate_inputs(*, docker: Path, docker_config: Path, proxy: Path,
                     fixture_root: Path, output: Path, image: str,
                     timeout: int) -> tuple[Path, Path, Path, dict[str, str]]:
    docker = _regular_file(docker, "Docker executable")
    docker_config = _directory(docker_config, "Docker config", empty=True)
    proxy = _regular_file(proxy, "path proxy")
    if image != PROBE_IMAGE:
        raise ValueError("diagnostic requires the pinned remote exec image")
    if not 1 <= timeout <= MAX_TIMEOUT_SECONDS:
        raise ValueError("diagnostic timeout is outside the bounded range")
    output = output.expanduser().absolute()
    if not output.is_absolute() or output.exists() or output.is_symlink():
        raise ValueError("diagnostic output must be a new absolute path")
    paths = _prepare_fixture_root(fixture_root)
    roots = [Path(path).resolve() for path in paths.values()]
    if any(output.resolve(strict=False) == root or output.resolve(strict=False).is_relative_to(root) for root in roots):
        raise ValueError("diagnostic output must not be inside a mounted fixture root")
    return docker, docker_config, proxy, paths


def _stage_summary(process: Mapping[str, Any], *, passed: bool,
                   **extra: Any) -> dict[str, Any]:
    return {"passed": passed, "process": dict(process), **extra}


def _not_run_process() -> dict[str, Any]:
    return {
        "process_started": False,
        "exit_code": None,
        "timed_out": False,
        "stdin_write_failed": False,
        "stdout_bytes": 0,
        "stderr_bytes": 0,
        "stdout_drained": True,
        "stderr_drained": True,
        "stdout_read_error": False,
        "stderr_read_error": False,
        "stdout_truncated": False,
        "stderr_truncated": False,
        "stderr_nonempty": False,
        "launch_error": None,
    }


def _telemetry_summary(path: Path) -> dict[str, Any]:
    base: dict[str, Any] = {
        "available": False,
        "schema_version": None,
        "schema_valid": False,
        "complete": False,
        "requests_seen": 0,
        "requests_forwarded": 0,
        "responses_seen": 0,
        "responses_forwarded": 0,
        "responses_matched": 0,
        "responses_unmatched": 0,
        "pending_request_ids": 0,
        "request_write_failures": 0,
        "request_mapping_rejections": 0,
        "response_mapping_rejections": 0,
        "child_exit_code": None,
        "child_stderr_bytes": 0,
        "child_stderr_nonempty": False,
        "child_stderr_truncated": False,
        "child_stderr_read_error": False,
        "child_stderr_drained": False,
        "mapping_clean": False,
        "correlated": False,
    }
    if path.is_symlink() or not path.is_file():
        return base
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        _validate_startup_telemetry_snapshot(value)
        valid = True
    except (OSError, UnicodeDecodeError, ValueError, json.JSONDecodeError):
        return base
    if not isinstance(value, dict):
        return base
    for key in (
        "requests_seen", "requests_forwarded", "responses_seen", "responses_forwarded",
        "responses_matched", "responses_unmatched", "pending_request_ids",
        "request_write_failures", "request_mapping_rejections", "response_mapping_rejections",
    ):
        if type(value.get(key)) is int and value[key] >= 0:
            base[key] = value[key]
    base.update({
        "available": True,
        "schema_version": value.get("schema_version"),
        "schema_valid": valid,
        "complete": bool(_proxy_telemetry_ready(value)),
        "child_exit_code": value.get("child_exit_code") if type(value.get("child_exit_code")) is int else None,
    })
    for key in ("child_stderr_bytes",):
        if type(value.get(key)) is int and value[key] >= 0:
            base[key] = value[key]
    for key in (
        "child_stderr_nonempty", "child_stderr_truncated",
        "child_stderr_read_error", "child_stderr_drained",
    ):
        if type(value.get(key)) is bool:
            base[key] = value[key]
    base["mapping_clean"] = (
        base["request_mapping_rejections"] == 0
        and base["response_mapping_rejections"] == 0
    )
    base["correlated"] = (
        base["responses_unmatched"] == 0 and base["pending_request_ids"] == 0
    )
    return base


def _run_rpc_variant(*, label: str, docker: Path, config: Path,
                     proxy: Path | None, docker_args: list[str],
                     name: str, telemetry_path: Path | None,
                     timeout: int) -> dict[str, Any]:
    observation = _initialize_observation()
    response_event = threading.Event()
    environment = _safe_environment(config)
    if proxy is None:
        command = _docker_command(docker, config, *docker_args)
        stderr_visibility = "bounded-in-memory"
    else:
        command = [
            sys.executable, "-B", str(proxy), "--docker", str(docker),
            "--telemetry-file", str(telemetry_path), "--", *docker_args,
        ]
        stderr_visibility = "proxy-child-stderr-bounded-counters"
    process, _ = _run_process(
        command, env=environment, timeout=timeout, input_data=INITIALIZE_REQUEST,
        on_stdout_line=lambda line: _observe_initialize_line(line, observation, response_event),
        response_event=response_event, wait_for_response=True,
    )
    cleanup = _cleanup_container(docker, config, name)
    telemetry = _telemetry_summary(telemetry_path) if telemetry_path is not None else None
    passed = _rpc_passed(process, observation, cleanup, telemetry)
    return {
        "label": label,
        "passed": passed,
        "skipped": False,
        "process": process,
        "response": observation,
        "cleanup": cleanup,
        "telemetry": telemetry,
        "stderr_visibility": stderr_visibility,
    }


def run(*, docker: Path, docker_config: Path, proxy: Path,
        fixture_root: Path, output: Path, image: str = PROBE_IMAGE,
        timeout: int = DEFAULT_TIMEOUT_SECONDS) -> dict[str, Any]:
    """Run the bounded direct/proxy differential fixture once."""
    docker, docker_config, proxy, paths = _validate_inputs(
        docker=docker, docker_config=docker_config, proxy=proxy,
        fixture_root=fixture_root, output=output, image=image, timeout=timeout,
    )
    token = uuid.uuid4().hex[:12]
    lifecycle_id = f"remote-child-{token}-lifecycle"
    direct_id = f"remote-child-{token}-direct"
    proxy_id = f"remote-child-{token}-proxy"
    lifecycle_args = _canonical_docker_args(paths, image, lifecycle_id)
    direct_args = _canonical_docker_args(paths, image, direct_id)
    proxy_args = _canonical_docker_args(paths, image, proxy_id)
    lifecycle_name = _name_from_args(lifecycle_args)
    direct_name = _name_from_args(direct_args)
    proxy_name = _name_from_args(proxy_args)
    telemetry_path = output.with_name(output.name + ".proxy-telemetry.json")
    if telemetry_path.exists() or telemetry_path.is_symlink():
        raise ValueError("diagnostic telemetry sidecar must be new")

    stages: dict[str, Any] = {}
    info, _ = _run_process(
        _docker_command(docker, docker_config, "info", "--format", "{{.ServerVersion}}"),
        env=_safe_environment(docker_config), timeout=timeout,
    )
    stages["docker-access"] = _stage_summary(
        info, passed=_command_ok(info) and info["stdout_bytes"] > 0,
    )
    if stages["docker-access"]["passed"]:
        inspect_image, image_sample = _run_process(
            _docker_command(docker, docker_config, "image", "inspect", image, "--format", "{{.Id}}"),
            env=_safe_environment(docker_config), timeout=timeout,
        )
    else:
        inspect_image, image_sample = _not_run_process(), b""
    image_observed = image_sample.strip() == image.encode("ascii")
    stages["image-inspect"] = _stage_summary(
        inspect_image,
        passed=_command_ok(inspect_image) and image_observed,
        image_id_observed=image_observed,
    )

    if stages["docker-access"]["passed"] and stages["image-inspect"]["passed"]:
        name_presence = _container_presence(docker, docker_config, lifecycle_name)
    else:
        name_presence = {"status": "not-run", "absent": False}
    lifecycle_name_available = name_presence["status"] == "available"
    lifecycle_create: dict[str, Any] = {
        "process": _not_run_process(),
        "container": {"available": False, "owned": False, "status": "not-run", "exit_code": None},
        "cleanup": {"status": "not-run", "verified": False},
    }
    lifecycle_start: dict[str, Any] = {
        "process": _not_run_process(),
        "marker_observed": False,
        "cleanup": {"status": "not-run", "verified": False},
    }
    lifecycle_passed = False
    if lifecycle_name_available:
        create_process, _ = _run_process(
            _docker_command(
                docker, docker_config,
                *_lifecycle_create_args(lifecycle_args, image),
            ),
            env=_safe_environment(docker_config), timeout=timeout,
        )
        container = _inspect_named_container(docker, docker_config, lifecycle_name)
        lifecycle_create = _stage_summary(
            create_process,
            passed=_command_ok(create_process)
            and create_process["stdout_bytes"] > 0
            and container.get("available") is True
            and container.get("owned") is True
            and container.get("status") == "created",
            container=container,
            cleanup={"status": "deferred", "verified": False},
        )
        if lifecycle_create["passed"]:
            start_process, start_sample = _run_process(
                _docker_command(docker, docker_config, "start", "-a", lifecycle_name),
                env=_safe_environment(docker_config), timeout=timeout,
            )
            lifecycle_cleanup = _cleanup_container(docker, docker_config, lifecycle_name)
            lifecycle_start = _stage_summary(
                start_process,
                passed=_command_ok(start_process)
                and start_sample == LIFECYCLE_MARKER
                and lifecycle_cleanup.get("verified") is True,
                marker_observed=start_sample == LIFECYCLE_MARKER,
                cleanup=lifecycle_cleanup,
            )
            lifecycle_passed = bool(lifecycle_start["passed"])
        else:
            lifecycle_create["cleanup"] = _cleanup_container(docker, docker_config, lifecycle_name)
    stages["container-create"] = {
        "passed": bool(lifecycle_name_available and lifecycle_create.get("passed") is True),
        "name_available": lifecycle_name_available,
        "name_check_status": name_presence["status"],
        **lifecycle_create,
    }
    stages["container-start"] = {
        "passed": lifecycle_passed,
        **lifecycle_start,
    }

    direct: dict[str, Any] = {
        "label": "direct",
        "passed": False,
        "skipped": not lifecycle_passed,
        "process": _not_run_process(),
        "response": _initialize_observation(),
        "cleanup": {"status": "not-run", "verified": False},
        "telemetry": None,
        "stderr_visibility": "bounded-in-memory",
    }
    proxy_result: dict[str, Any] = {
        "label": "proxy",
        "passed": False,
        "skipped": not lifecycle_passed,
        "process": _not_run_process(),
        "response": _initialize_observation(),
        "cleanup": {"status": "not-run", "verified": False},
        "telemetry": None,
        "stderr_visibility": "proxy-child-stderr-bounded-counters",
    }
    if lifecycle_passed:
        direct = _run_rpc_variant(
            label="direct", docker=docker, config=docker_config, proxy=None,
            docker_args=direct_args, name=direct_name, telemetry_path=None, timeout=timeout,
        )
        proxy_result = _run_rpc_variant(
            label="proxy", docker=docker, config=docker_config, proxy=proxy,
            docker_args=proxy_args, name=proxy_name, telemetry_path=telemetry_path,
            timeout=timeout,
        )
    stages["direct-exec-server-initialize"] = direct
    stages["proxy-exec-server-initialize"] = proxy_result

    direct_success = bool(direct.get("passed") is True)
    proxy_success = bool(proxy_result.get("passed") is True)
    direct_response = direct.get("response", {})
    proxy_response = proxy_result.get("response", {})
    comparison = {
        "docker_args_semantically_equal": _semantic_args(direct_args) == _semantic_args(proxy_args),
        "mount_destinations_equal": (
            _mount_destinations(direct_args)
            == _mount_destinations(proxy_args)
            == MOUNT_DESTINATIONS
        ),
        "initialize_contract": "remote-exec-server-clientName",
        "direct_initialize_success": direct_response.get("initialize_successes") == 1,
        "proxy_initialize_success": proxy_response.get("initialize_successes") == 1,
        "initialize_result_equivalent": (
            direct_response.get("initialize_successes") == proxy_response.get("initialize_successes") == 1
            and direct_response.get("initialize_error_codes") == proxy_response.get("initialize_error_codes") == {}
        ),
        "startup_equivalent": direct_success and proxy_success,
    }
    if not stages["docker-access"]["passed"]:
        failure_stage = "docker-access"
    elif not stages["image-inspect"]["passed"]:
        failure_stage = "image-inspect"
    elif not stages["container-create"]["passed"]:
        failure_stage = "container-create"
    elif not stages["container-start"]["passed"]:
        failure_stage = "container-start"
    elif not direct_success:
        failure_stage = "direct-exec-server-initialize"
    elif not proxy_success:
        failure_stage = "proxy-exec-server-initialize"
    elif not comparison["startup_equivalent"]:
        failure_stage = "direct-proxy-comparison"
    else:
        failure_stage = None
    result = {
        "schema_version": REPORT_SCHEMA_VERSION,
        "verdict": "remote-child-differential-ready" if failure_stage is None else "remote-child-differential-blocked",
        "failure_stage": failure_stage,
        "image_id": image,
        "contract": {
            "network_mode": "none",
            "include_local": False,
            "mount_destinations": list(MOUNT_DESTINATIONS),
            "candidate_env_keys": [
                "HOME", "CODEX_HOME", "PATH", "PYTHONDONTWRITEBYTECODE", "TMPDIR",
            ],
            "initialize_contract": "remote-exec-server-clientName",
            "app_server_started": False,
            "authentication_attempted": False,
            "model_execution_attempted": False,
        },
        "stages": stages,
        "comparison": comparison,
        "privacy": {
            "request_payload_preserved": False,
            "response_payload_preserved": False,
            "host_paths_preserved": False,
            "raw_stderr_preserved": False,
            "credential_files_read": False,
            "control_home_read": False,
        },
        "scope": (
            "model-free pinned Docker remote exec-server lifecycle and direct-vs-proxy "
            "initialize comparison; not App Server thread/start compatibility, authentication, "
            "model smoke, or behavioral evaluation evidence"
        ),
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docker", type=Path, required=True)
    parser.add_argument("--docker-config", type=Path, required=True)
    parser.add_argument("--path-proxy", type=Path, required=True)
    parser.add_argument("--fixture-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--image", default=PROBE_IMAGE)
    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT_SECONDS)
    args = parser.parse_args()
    try:
        result = run(
            docker=args.docker, docker_config=args.docker_config, proxy=args.path_proxy,
            fixture_root=args.fixture_root, output=args.output, image=args.image,
            timeout=args.timeout,
        )
    except (ValueError, OSError, subprocess.SubprocessError) as error:
        print(json.dumps({
            "schema_version": REPORT_SCHEMA_VERSION,
            "verdict": "remote-child-differential-invalid-input",
            "failure_stage": "input-validation",
            "error_code": _safe_error_code(error),
            "report_written": False,
        }, ensure_ascii=False, indent=2))
        return 2
    print(json.dumps({
        "schema_version": result["schema_version"],
        "verdict": result["verdict"],
        "failure_stage": result["failure_stage"],
        "report_written": True,
    }, ensure_ascii=False, indent=2))
    return 0 if result["verdict"] == "remote-child-differential-ready" else 1


if __name__ == "__main__":
    raise SystemExit(main())
